name: linkmark_app
description: It is an application that stores links.
version: 1.0.0+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: '>=1.22.0'

dependency_overrides:
  sqflite: 1.3.1+2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # For DateTime and l10n
  intl: ^0.16.1

  # For Architecture
  flutter_hooks: ^0.15.0
  hooks_riverpod: ^0.12.1

  # For Networking
  dio: ^3.0.10
  dio_http_cache: ^0.2.11
  dio_firebase_performance: ^0.2.0

  # For Model
  json_serializable: ^3.5.0
  freezed_annotation: ^0.12.0

  # Convert between Enum and String
  enum_to_string: ^1.0.14

  # For UIs
  gap: ^1.2.0
  cupertino_icons: ^1.0.0
  google_fonts: ^1.1.1
  cached_network_image: ^2.3.3
  flutter_svg: ^0.19.2+1
  animations: ^1.1.2
  modal_bottom_sheet: ^1.0.0+1
  flutter_signin_button: ^1.1.0
  shimmer: ^1.1.2
  implicitly_animated_reorderable_list: ^0.3.2
  flutter_slidable: ^0.5.7

  # For Utilities
  get: ^3.17.1
  simple_logger: ^1.7.0

  # For Share URL
  receive_sharing_intent: ^1.4.2
  share: '>=0.6.5+4 <2.0.0'

  # For Fetch Metadata
  metadata_fetch: ^0.3.3

  # For Launch URL
  url_launcher: ^5.7.10

  # For Validate
  validators: ^2.0.1

  # For Firebase
  firebase_core: ^0.5.3
  firebase_analytics: ^6.3.0
  firebase_auth: ^0.18.4+1
  firebase_crashlytics: ^0.2.4
  firebase_database: ^4.4.0

  # For Google SignIn
  google_sign_in: ^4.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.4
  flutter_gen: ^1.3.1

  # For Model
  freezed: ^0.12.2

  # For Analyzer
  effective_dart: ^1.3.0

  # For Testing
  mockito:
  image_test_utils:
  remove_from_coverage: ^1.0.7

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/

#  fonts:
#    - family: Rotunda
#      fonts:
#        - asset: assets/fonts/Rotunda-Bold.otf
#          weight: 700
